import { describe, expect, it } from "vitest";

import { sha256Hex } from "../../rendering/checksum";
import {
  DIAGNOSTIC_RAW_COLOUR_MODE,
  PHOTO_PAPERS3_SLIDESHOW_GRAY16_MODE,
  diagnosticAppImageModeForRenderIntent,
  ditherPaperS3SlideshowGray16ToStableRgb,
  enhancePaperS3SlideshowPhotoLuma,
  quantizePaperS3StableLuma,
} from "./diagnostic-raw-colour";

const BAYER_VALUES = Array.from({ length: 16 }, (_, index) => index);

function m5gfxLevel(luma: number, bayer: number): number {
  return Math.max(0, Math.min(15, (luma + bayer - 8) >> 4));
}

describe("PaperS3 slideshow photo gray16 mode", () => {
  it("selects the slideshow pipeline only for explicit photo intent", () => {
    expect(PHOTO_PAPERS3_SLIDESHOW_GRAY16_MODE)
      .toBe("photo-papers3-slideshow-gray16-rgb-png-v3");
    expect(diagnosticAppImageModeForRenderIntent("photo"))
      .toBe(PHOTO_PAPERS3_SLIDESHOW_GRAY16_MODE);
    for (const intent of ["map", "graphic", undefined] as const) {
      expect(diagnosticAppImageModeForRenderIntent(intent))
        .toBe(DIAGNOSTIC_RAW_COLOUR_MODE);
    }
  });

  it("matches Pillow autocontrast/contrast/unsharp bytes from process_images.py", () => {
    const width = 16;
    const height = 16;
    const source = Buffer.from(
      Array.from({ length: width * height }, (_, index) => {
        const x = index % width;
        const y = Math.floor(index / width);
        return (x * 29 + y * 47 + x * y * 3) % 256;
      }),
    );
    const enhanced = enhancePaperS3SlideshowPhotoLuma(source, width, height);

    // Generated by Pillow 12.1 with the exact slideshow stages:
    // autocontrast(cutoff=(0.5,0.5)), Contrast(1.08), then
    // UnsharpMask(radius=1, percent=65, threshold=3).
    expect(sha256Hex(enhanced)).toBe(
      "34df4c4f9e74762ac8b8383c5bce002362509c6cbc22f0debad8a98c996eb35d",
    );
    expect([...enhanced.subarray(0, 16)]).toEqual([
      0, 2, 34, 66, 100, 139, 183, 243,
      255, 0, 0, 35, 71, 107, 150, 209,
    ]);

    const stableRgb = ditherPaperS3SlideshowGray16ToStableRgb(
      enhanced,
      width,
      height,
    );
    // Same pixels as process_images.py quantize_gray16(), re-encoded from
    // 0,17,...,255 indices to stable M5GFX RGB centres 8,24,...,248.
    expect(sha256Hex(stableRgb)).toBe(
      "5ec24540176388c7101e87f540be99f3df7d750fb903475ad53422fc0a82053f",
    );
  });

  it("maps every byte to a stable native-level centre at every Bayer position", () => {
    const centres = BAYER_VALUES.map((level) => 8 + level * 16);
    expect(BAYER_VALUES.map((level) => quantizePaperS3StableLuma(level * 17)))
      .toEqual(centres);
    expect(quantizePaperS3StableLuma(-10)).toBe(8);
    expect(quantizePaperS3StableLuma(255)).toBe(248);

    const reachable = new Set<number>();
    for (let source = 0; source <= 255; source += 1) {
      const stable = quantizePaperS3StableLuma(source);
      expect(centres).toContain(stable);
      const levels = BAYER_VALUES.map((bayer) => m5gfxLevel(stable, bayer));
      expect(new Set(levels).size).toBe(1);
      reachable.add(levels[0]);
    }
    expect([...reachable].sort((left, right) => left - right))
      .toEqual(BAYER_VALUES);

    for (let level = 0; level < centres.length; level += 1) {
      expect(BAYER_VALUES.map((bayer) => m5gfxLevel(centres[level], bayer)))
        .toEqual(Array(16).fill(level));
    }
  });
});
